//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PISServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.OriginUser = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string FacebookId { get; set; }
        public string LinkedInId { get; set; }
        public string Mail { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<User> OriginUser { get; set; }
        public virtual User Friends { get; set; }
    }
}
