//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PisDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int Id { get; set; }
        public string DeviceId { get; set; }
        public string Platform { get; set; }
        public int UserId { get; set; }
        public bool Active { get; set; }
        public System.DateTime Date { get; set; }
        public string Language { get; set; }
        public short Badge { get; set; }
        public Nullable<short> BadgeAccept { get; set; }
        public Nullable<short> BadgeSolicitation { get; set; }
    
        public virtual User User { get; set; }
    }
}
