//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PisDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Share
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int UserId1 { get; set; }
        public System.DateTime Date { get; set; }
        public bool Active { get; set; }
    
        public virtual User UserWith { get; set; }
        public virtual User UserFrom { get; set; }
    }
}
