//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PisDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Session = new HashSet<Session>();
            this.Event = new HashSet<Event>();
            this.FriendsOf = new HashSet<User>();
            this.FriendsFrom = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string FacebookId { get; set; }
        public string LinkedInId { get; set; }
        public string Mail { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Session> Session { get; set; }
        public virtual UserPosition UserPosition { get; set; }
        public virtual ICollection<Event> Event { get; set; }
        public virtual ICollection<User> FriendsOf { get; set; }
        public virtual ICollection<User> FriendsFrom { get; set; }
    }
}
